const { Client, MessageEmbed } = require('discord.js');

exports.run = async (Client, Message, Args) => {
console.log(Message.author.tag + "used botstats")
const botver = "1.1"; //bot version string
const botstarted=Date(); //records time at which bot booted up
const statsembed = new MessageEmbed()
			.setTitle("Bot Statistics")
			.setDescription("**Servers: **" + Client.guilds.cache.size + "\n **Bot Version: **" + botver + "\n **Last Startup: **" + botstarted)
			.setFooter("Generated by " + Client.user.tag)
			.setColor(0xf6bf54)
			.setTimestamp()

Message.channel.send({ embeds: [statsembed] });
    
}

exports.config = {
name: "botstats",
aliases: [""],
}